version: 2
registries:
  git-github-io:
    type: git
    url: https://github.io
    username: jpelaezClub
    password: "${{secrets.GIT_GITHUB_IO_PASSWORD}}"
  git-wordpress-com:
    type: git
    url: https://wordpress.com
    username: jpelaezblog01
    password: "${{secrets.GIT_WORDPRESS_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: web-ext
    versions:
    - 5.5.0
    - 6.0.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: grunt-replace
    versions:
    - 2.0.0
  - dependency-name: webextension-polyfill
    versions:
    - 0.7.0
  - dependency-name: grunt
    versions:
    - 1.3.0
  registries:
  - git-github-io
  - git-wordpress-com
